### PR TITLE
i/6169: Enhance Media Embed plugin icon

### PR DESCRIPTION
**Pull request by panr**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Enhanced Media Embed plugin icon. Closes ckeditor/ckeditor5#6168.

After fixes:
image

--
Related to: ckeditor/ckeditor5#6169

### CODE REVIEW

**Comment by oleq** [comment]
Why was the media icon horizontally squashed in this PR? It no longer resembles a film strip.

image

**Comment by panr** [comment]
> Why was the media icon horizontally squashed in this PR?

I found the icon is a little bit out of the rhythm of the other icons... Maybe square shaped version was a mistake, but at least I want it to be in the middle of the canvas. I'll restore its rect shape 👍

**Comment by Reinmar** [comment]
Agree with Olek. It stopped resembling a film strip that much. 

My OCD also tells me that having identical boxes for all icons is good. However, I did like the previous table icon (which was slightly bigger) and the wider media embed because... they give some flow. The box is broken, but they looked more correct to me before the change. Right now, they look a bit too small.

**Comment by panr** [comment]
@Reinmar related to your answer https://github.com/ckeditor/ckeditor5/issues/6168#issuecomment-588986922

**Comment by panr** [comment]
image

**Comment by panr** [comment]
> Maybe we could move the entire icon leaving the holes in place?

OK, I made that version. It looks a little bit off, but maybe it will work well on low-ppi screens. Could you check it?

**Comment by oleq** [comment]
Can you resolve conflicts?

**Comment by panr** [comment]
@oleq done

**Pull request merged**
