### PR TITLE
Display media-embed label hint immediately

### LINKED ISSUE #5: How to improve the UI?
ATM the insertion/editing is via the "dropform" attached to the toolbar button

image

It's been simple to implent and works for MVP but:
* **it makes no sense with the balloon toolbar (editor), which requires a non-collapsed selection to show up and the media embedding should definitely be available for collapsed selections,**
* sometimes it's visually far from the media in the content and it makes editing inconvenient,
   * should we allow media editing anyway?

Some options: 
* if we decided to attach a form with the URL editing field to straight to the media in the content, we'd have to insert a blank (empty, URL–less) media first and then edit its URL, which is an implementation hassle,
   * also what if the user decides they dont want it any more after they pressed the toolbar button? How to treat it in the model/collaboration? Should it be gone as soon as they blur the media? Or maybe removed manually?
* the insertion similar to the Link feature makes no sense because the media is not inserted at the selection (just like the link) where the balloon's arrow is pointing; it's inserted as a next block, so this would be visually inaccurate

Down the road:
* still... we may need a balloon attached to the media in the future because of media styles (similar to image styles) 
image
* the autoembeding could help us out because it's a faster path for the user to do things and with that implemented, we could keep the UI very simple

### PR DESCRIPTION
**Pull request by dkonopka**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: The help text under the media URL input should be displayed when it's empty. The quick insertion tip should pop out when the user started typing in the input (see #5).

### CODE REVIEW

**Comment by oleq** [comment]
TBH it's not exactly what #5 is about. It's more about users not understanding that the input is the place they should paste the media URL rather than displaying a "quick–paste hint", which is a different story.

I was thinking more about "Paste the media URL here" under the input (when it's empty), then "Paste the URL..." when it's not empty.

**Comment by dkonopka** [comment]
I guess this PR won't fix #5 actually because it will only improve UX of input instead of adding balloon to the media-embed.

> we may need a balloon attached to the media in the future because of media styles (similar to image styles)

Anyway your proposal of:
> I was thinking more about "Paste the media URL here" under the input (when it's empty), then "Paste the URL..." when it's not empty.

is better idea instead of current solution, I'll fix it.

**Comment by oleq** [comment]
Improved the UX

kapture 2019-01-03 at 15 30 17

**Comment by dkonopka** [comment]
"Tip part" is really good idea 👍

**Pull request merged**
